// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0WV7oIkcFkj-7IK7dADwzzFRTlrdQKKU',
    appId: '1:556017055999:web:617a0365204cd9ac15f4ca',
    messagingSenderId: '556017055999',
    projectId: 'fruitapp-beeff',
    authDomain: 'fruitapp-beeff.firebaseapp.com',
    storageBucket: 'fruitapp-beeff.firebasestorage.app',
    measurementId: 'G-4R5WCVKMR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDID8VH93BUI2xRXHLOKdQKXqUAHlAFo84',
    appId: '1:556017055999:android:714698a87219197515f4ca',
    messagingSenderId: '556017055999',
    projectId: 'fruitapp-beeff',
    storageBucket: 'fruitapp-beeff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZW-HSO39oj7v8pC-_tO_PilvdTdcRRgc',
    appId: '1:556017055999:ios:639d5cea778817db15f4ca',
    messagingSenderId: '556017055999',
    projectId: 'fruitapp-beeff',
    storageBucket: 'fruitapp-beeff.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZW-HSO39oj7v8pC-_tO_PilvdTdcRRgc',
    appId: '1:556017055999:ios:639d5cea778817db15f4ca',
    messagingSenderId: '556017055999',
    projectId: 'fruitapp-beeff',
    storageBucket: 'fruitapp-beeff.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0WV7oIkcFkj-7IK7dADwzzFRTlrdQKKU',
    appId: '1:556017055999:web:8a375fea88a6e32e15f4ca',
    messagingSenderId: '556017055999',
    projectId: 'fruitapp-beeff',
    authDomain: 'fruitapp-beeff.firebaseapp.com',
    storageBucket: 'fruitapp-beeff.firebasestorage.app',
    measurementId: 'G-5H0EG9B2ZH',
  );
}
